### ISSUE TITLE
Error: Call to undefined method JsonResponse::create()

### ISSUE THREAD

**Issue by mstenta** [Regen-Digital/farm_farmlab#8]
Saw this error in logs recently:

`Error: Call to undefined method Symfony\Component\HttpFoundation\JsonResponse::create() in Drupal\farm_farmlab\Controller\GeojsonController->boundaries() (line 72 of /opt/drupal/web/modules/farm_farmlab/src/Controller/GeojsonController.php).`

This is probably related to the Drupal 10 upgrade.

Similar issue in the Subrequests module for reference: https://www.drupal.org/project/subrequests/issues/3362424

**Comment by paul121** [comment]
This has been fixed in [1.0.0-beta4](https://git.drupalcode.org/project/farm_farmlab/-/blob/1.x/CHANGELOG.md?ref_type=heads#100-beta4-2024-08-16), released on drupal gitlab.

I'm going to deprecate/archive this repo and move to only managing this module in drupal gitlab since Regen Digital is no longer supporting this work.
